version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/naija_verify
      USE_MEMORY_DB: "false"
    depends_on:
      - mongo
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo-data:
